### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [Luuk3333/FFA320Connector#7] opened 2019-01-13 19:15 UTC
Hey Luuk3333, can you make a new RELEASE please ? 
Because many people keep downloading the 1.1.6 but the MASTER has received many fixes...
(For exemple the release version breaks BSS engine volumes when on the master it appears OK)

**Comment by Luuk3333** [comment] 2019-01-14 16:06
Hey!

The master has just a few commits since the 1.1.6 release (your pull request and some readme changes), so the engine volume problem is probably caused by something else.
I'm currently working on making the build process more streamlined so further development will be more accessible. Things like removing source duplicates and excluding files from git. Will release a new version once that has been completed.

**Comment by Sakarias-Longhorn** [comment] 2019-01-14 16:10
Hey Luuk ;)
Please have a quick look at this thread
https://forums.x-plane.org/index.php?/forums/topic/168039-fixed-bss-soundpack-latest-connector-engine-rumble-noise/

Basically, if we download 1.1.6, the 4 datarefs are commented out, but on the CLONE/DOWNLOAD Master, they're uncommented.

**Comment by Luuk3333** [comment] 2019-01-14 16:51
Ah, I see now. Since it's correct (uncommented) in the current config it will be included in the next release.

**Closed** 2019-01-15 12:22 UTC
